name: consult_anilist_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

dependencies:
  args: ^2.3.0
  shelf: ^1.4.1
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^0.13.0
 
