name: consult_anilist_api
description: A server app using the shelf package and Docker.
version: 1.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

dependencies:
  args: ^2.3.0
  shelf: ^1.1.1
  http: ^1.1.0
  shelf_router: ^1.1.3
  mongo_dart: ^0.9.1
  dotenv: ^4.1.0
  intl: ^0.18.1
  translator: ^1.0.0

dev_dependencies:
  
 
